apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: php-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/taiseerhussein/php-hello.git'
    path: apps/php/overlays/prod
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: php-hello-prod
  syncPolicy:
    automated:
      prune: true
